/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DownloadIndexRouteImport } from './routes/download/index'
import { Route as ConfigIndexRouteImport } from './routes/config/index'
import { Route as indexIndexRouteImport } from './routes/(index)/index'
import { Route as SongSrcRouteImport } from './routes/song/$src'

const DownloadIndexRoute = DownloadIndexRouteImport.update({
  id: '/download/',
  path: '/download/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigIndexRoute = ConfigIndexRouteImport.update({
  id: '/config/',
  path: '/config/',
  getParentRoute: () => rootRouteImport,
} as any)
const indexIndexRoute = indexIndexRouteImport.update({
  id: '/(index)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SongSrcRoute = SongSrcRouteImport.update({
  id: '/song/$src',
  path: '/song/$src',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/song/$src': typeof SongSrcRoute
  '/': typeof indexIndexRoute
  '/config': typeof ConfigIndexRoute
  '/download': typeof DownloadIndexRoute
}
export interface FileRoutesByTo {
  '/song/$src': typeof SongSrcRoute
  '/': typeof indexIndexRoute
  '/config': typeof ConfigIndexRoute
  '/download': typeof DownloadIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/song/$src': typeof SongSrcRoute
  '/(index)/': typeof indexIndexRoute
  '/config/': typeof ConfigIndexRoute
  '/download/': typeof DownloadIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/song/$src' | '/' | '/config' | '/download'
  fileRoutesByTo: FileRoutesByTo
  to: '/song/$src' | '/' | '/config' | '/download'
  id: '__root__' | '/song/$src' | '/(index)/' | '/config/' | '/download/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SongSrcRoute: typeof SongSrcRoute
  indexIndexRoute: typeof indexIndexRoute
  ConfigIndexRoute: typeof ConfigIndexRoute
  DownloadIndexRoute: typeof DownloadIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/download/': {
      id: '/download/'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config/': {
      id: '/config/'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof ConfigIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(index)/': {
      id: '/(index)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof indexIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/song/$src': {
      id: '/song/$src'
      path: '/song/$src'
      fullPath: '/song/$src'
      preLoaderRoute: typeof SongSrcRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  SongSrcRoute: SongSrcRoute,
  indexIndexRoute: indexIndexRoute,
  ConfigIndexRoute: ConfigIndexRoute,
  DownloadIndexRoute: DownloadIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
